# Generated by Django 5.2 on 2025-04-13 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0002_remove_cliente_email_cliente_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos_cargados', to=settings.AUTH_USER_MODEL),
        ),
    ]
