# Generated by Django 5.2 on 2025-04-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Sube aquí tu foto de perfil', null=True, upload_to='avatars/'),
        ),
    ]
