# Generated by Django 5.2 on 2025-04-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_vendedor_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento', null=True),
        ),
    ]
